name: build

on:
  push:
    paths-ignore:
      - '**/*.*md'
  pull_request:
    paths-ignore:
      - '**/*.*md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - run: |
        cd NowWhat
        dotnet tool restore
        dotnet test
