name: build

on:
  push:
    paths-ignore:
      - '**/*.*md'
  pull_request:
    paths-ignore:
      - '**/*.*md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - run: dotnet tool restore
    - name: Check `dotnet run` # verify this builds/doesn't crash
      run: |
        cd NowWhat
        dotnet run
    - name: Test suite
      run: |
        cd Test
        NOWWHAT_GITHUB_TOKEN=${{secrets.NOWWHAT_GITHUB_TOKEN}} dotnet test
